name: Run Daily Python Script

on:
  schedule:
    - cron: '35 6 * * *'  # Runs daily at 6:00 AM UTC
  workflow_dispatch:     # Allows manual run from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12.6
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.6'  # or your required version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python currency_exchange.py
